### ISSUE TITLE
Package name is "@walmartlabs/nocktor", should be "nocktor"

### ISSUE THREAD

**Issue by ianwsperber** [walmartlabs/nocktor#1]
Package name is `@walmartlabs/nocktor`. Since this is now a publicly accessible NPM module I assume you'll want to change the name to `nocktor`, so folks may `require('nocktor')` 😄 

See https://github.com/walmartlabs/nocktor/blob/master/package.json#L2

**Comment by mosabua** [comment]
No .. it should stay with a namespace for walmartlabs .. just like this project is on github at https://github.com/walmartlabs/nocktor

**Comment by ianwsperber** [comment]
Hi @mosabua! If WalmartLabs wants to leave the package under the `@walmartlabs` that's a valid decision, but I believe it is more common to publish NPM packages without a namespace unless you have a specific reason to do so (internal module, avoiding naming collision, etc). Moreover WalmartLabs has published packages without the `@walmartlabs` namespace in the past (see below), all leading me to conclude this may be a relic that precedes the OSS release.

https://github.com/walmartlabs/thorax/blob/master/package.json#L2
https://github.com/walmartlabs/easy-fix/blob/master/package.json#L2
https://github.com/electrode-io/electrode/blob/master/package.json#L2

**Comment by mosabua** [comment]
We are working on a number of initiatives to foster and market our open source efforts and using our own namespace is part of this work. This is common in other systems and in some even enforced. I realize this has not been the case so far with our projects but going forward we are trying to do that for new projects. Feel free to reach out to arrange further discussions via opensource@walmartlabs.com

**Comment by ianwsperber** [comment]
Thanks @mosabua! Will close issue then since it seems like this was intentional :)
